# Nixpacks Configuration for Morvo AI Backend
# Production-ready Python FastAPI deployment

providers = ["python"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"
PORT = "8000"

[phases.install]
dependsOn = []
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "python main.py"

[environments.production]
# Removed as per the edit
