[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Enhanced deployment for MCP & A2A protocols
# Updated: 2025-06-07T12:46:00+03:00 - Added enhanced protocol support

[variables]
# Protocol Configuration
ENHANCED_PROTOCOLS_AVAILABLE = "true"
MCP_ENABLED = "true"
A2A_ENABLED = "true"

# Performance Tuning for Enhanced Agents
UVICORN_WORKERS = "2"
UVICORN_TIMEOUT_KEEP_ALIVE = "30"
UVICORN_MAX_REQUESTS = "1000"
ASYNCIO_TIMEOUT = "60"

# Logging Configuration
LOG_LEVEL = "INFO"
ENABLE_PROTOCOL_LOGGING = "true"
