[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main_new.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Updated: 2025-06-07T02:54:00+03:00 - Production ready with fixed dependencies
